apiVersion: v1
kind: Service
metadata:
  labels:
    app: teastore
    run: teastore-auth
  name: teastore-auth
  namespace: teastore
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: teastore-auth
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: teastore
    run: teastore-db
  name: teastore-db
  namespace: teastore
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    run: teastore-db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: teastore
    run: teastore-image
  name: teastore-image
  namespace: teastore
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: teastore-image
---
apiVersion: v1
kind: Service
metadata:
  name: teastore-lb
  namespace: teastore
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: teastore
    run: teastore-webui
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: teastore
    run: teastore-persistence
  name: teastore-persistence
  namespace: teastore
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: teastore-persistence
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: teastore
    run: teastore-recommender
  name: teastore-recommender
  namespace: teastore
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: teastore-recommender
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: teastore
    run: teastore-registry
  name: teastore-registry
  namespace: teastore
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: teastore-registry
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: teastore
    run: teastore-webui
  name: teastore-webui
  namespace: teastore
spec:
  ports:
  - nodePort: 30080
    port: 8080
    protocol: TCP
  selector:
    run: teastore-webui
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appdAppName: TeaStore
    instrument: appd-auto
  name: teastore-auth
  namespace: teastore
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-auth
  template:
    metadata:
      labels:
        app: teastore
        appdAppName: TeaStore
        instrument: appd-auto
        run: teastore-auth
    spec:
      containers:
      - env:
        - name: APPDYNAMICS_NETVIZ_AGENT_PORT
          value: "3892"
        - name: APPDYNAMICS_NETVIZ_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: HOST_NAME
          value: teastore-auth
        - name: REGISTRY_HOST
          value: teastore-registry
        image: descartesresearch/teastore-auth
        name: teastore-auth
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-db
  namespace: teastore
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-db
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-db
    spec:
      containers:
      - image: descartesresearch/teastore-db
        name: teastore-db
        ports:
        - containerPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appdAppName: TeaStore
    instrument: appd-auto
  name: teastore-image
  namespace: teastore
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-image
  template:
    metadata:
      labels:
        app: teastore
        appdAppName: TeaStore
        instrument: appd-auto
        run: teastore-image
    spec:
      containers:
      - env:
        - name: APPDYNAMICS_NETVIZ_AGENT_PORT
          value: "3892"
        - name: APPDYNAMICS_NETVIZ_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: HOST_NAME
          value: teastore-image
        - name: REGISTRY_HOST
          value: teastore-registry
        image: descartesresearch/teastore-image
        name: teastore-image
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appdAppName: TeaStore
    instrument: appd-auto
  name: teastore-persistence
  namespace: teastore
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-persistence
  template:
    metadata:
      labels:
        app: teastore
        appdAppName: TeaStore
        instrument: appd-auto
        run: teastore-persistence
    spec:
      containers:
      - env:
        - name: APPDYNAMICS_NETVIZ_AGENT_PORT
          value: "3892"
        - name: APPDYNAMICS_NETVIZ_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: HOST_NAME
          value: teastore-persistence
        - name: REGISTRY_HOST
          value: teastore-registry
        - name: DB_HOST
          value: teastore-db
        - name: DB_PORT
          value: "3306"
        image: descartesresearch/teastore-persistence
        name: teastore-persistence
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appdAppName: TeaStore
    instrument: appd-auto
  name: teastore-recommender
  namespace: teastore
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-recommender
  template:
    metadata:
      labels:
        app: teastore
        appdAppName: TeaStore
        instrument: appd-auto
        run: teastore-recommender
    spec:
      containers:
      - env:
        - name: APPDYNAMICS_NETVIZ_AGENT_PORT
          value: "3892"
        - name: APPDYNAMICS_NETVIZ_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: HOST_NAME
          value: teastore-recommender
        - name: REGISTRY_HOST
          value: teastore-registry
        image: descartesresearch/teastore-recommender
        name: teastore-recommender
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appdAppName: TeaStore
    instrument: appd-auto
  name: teastore-registry
  namespace: teastore
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-registry
  template:
    metadata:
      labels:
        app: teastore
        appdAppName: TeaStore
        instrument: appd-auto
        run: teastore-registry
    spec:
      containers:
      - env:
        - name: APPDYNAMICS_NETVIZ_AGENT_PORT
          value: "3892"
        - name: APPDYNAMICS_NETVIZ_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: HOST_NAME
          value: teastore-recommender
        image: descartesresearch/teastore-registry
        name: teastore-registry
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appdAppName: TeaStore
    instrument: appd-auto
  name: teastore-webui
  namespace: teastore
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-webui
  template:
    metadata:
      labels:
        app: teastore
        appdAppName: TeaStore
        instrument: appd-auto
        run: teastore-webui
    spec:
      containers:
      - env:
        - name: APPDYNAMICS_NETVIZ_AGENT_PORT
          value: "3892"
        - name: APPDYNAMICS_NETVIZ_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: HOST_NAME
          value: teastore-webui
        - name: REGISTRY_HOST
          value: teastore-registry
        image: descartesresearch/teastore-webui
        name: teastore-webui
        ports:
        - containerPort: 8080
