apiVersion: v1
kind: Service
metadata:
#  annotations:
#    ncp/internal_ip_for_policy: 100.64.208.237
#  labels:
#    zone: internal
  name: teastore-nodeport
  namespace: teastore
spec:
  type: NodePort
  selector:
    app: teastore
    run: teastore-webui
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32001
