apiVersion: v1
kind: Service
metadata:
  annotations:
    ncp/internal_ip_for_policy: 100.64.208.237
  creationTimestamp: "2020-05-15T20:15:51Z"
  labels:
    app.kubernetes.io/instance: xl-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx
    zone: internal
  name: nginx
  namespace: turbonomic
  ownerReferences:
  - apiVersion: charts.helm.k8s.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Xl
    name: xl-release
    uid: f59e2a46-cf2e-4d6a-9569-68ece06c3c3f
  resourceVersion: "3949484"
  selfLink: /api/v1/namespaces/turbonomic/services/nginx
  uid: 0033c4b0-74d5-4548-926b-77336b8e0281
spec:
  clusterIP: 10.100.200.46
  externalTrafficPolicy: Local
  healthCheckNodePort: 30493
  ports:
  - name: https-nginx
    nodePort: 30577
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: http-nginx
    nodePort: 30746
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: xl-release
    app.kubernetes.io/name: nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.254.43.177
