resources:
- teastore-clusterip.yaml
- teastore-load.yaml

patches:
- target:
    kind: Deployment
    name: teastore-auth|teastore-image|teastore-recommender|teastore-webui|teastore-persistence|teastore-registry
  patch: |-
            - op: add
              path: "/metadata/labels"
              value: { instrument: "appd-auto" , appdAppName: "TeaStore" }


configMapGenerator:
- name: load-script
  files:
  - teastore_browse_nogui.jmx

generatorOptions:
  disableNameSuffixHash: true
